# Logging configuration
logging:
  version: 1
  formatters:
    footballapi:
      format: "footballapi ETL - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: footballapi
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]